engines:
  duplication:
    enabled: true
    config:
      languages:
      - php
  fixme:
    enabled: true
  phpcodesniffer:
    enabled: true
    config:
      standard: "PSR1,PSR2"
  phpmd:
    enabled: true
    config:
      file_extensions: "php"
      rulesets: "unusedcode,codesize,naming,design,cleancode"

ratings:
  paths:
  - "**.php"

exclude_paths:
  - "tests/**/*"
  - "vendor/**/*"
