# use [ci skip] or [skip ci] to skip a build in Travis CI
language: php

git:
  depth: 5 # default is 50

php:
  - '7.0'
  - nightly

branches:
  except:
    - gh-pages

env:
  matrix:
    - PREFER="update --prefer-source --prefer-lowest --prefer-stable"
    - PREFER="update --prefer-source --prefer-stable"
    - PREFER="install"

matrix:
  allow_failures:
    - php: nightly

# see https://docs.travis-ci.com/user/trusty-ci-environment (tl;dr: newer hhvm version)
sudo: required
dist: trusty
group: edge

before_script:
  - travis_retry composer self-update
  - travis_retry composer $PREFER

script:
  - composer test

after_success:
  - travis_retry php vendor/bin/coveralls -v

notifications:
  irc:
    channels:
      - chat.freenode.net#honeybee
    on_success: always
    on_failure: always
    use_notice: false
    skip_join: false
